--Especificação (Specification)
CREATE OR REPLACE PACKAGE PKG_CALCULADORA IS
    PROCEDURE CALCULA_REAJUSTE(P_SAL_ATUAL IN NUMBER);
    FUNCTION CONVERTE_DOLAR(V_DOLAR IN NUMBER) RETURN NUMBER;
END PKG_CALCULADORA;
/

--Corpo (Body)
CREATE OR REPLACE PACKAGE BODY PKG_CALCULADORA IS
    PROCEDURE CALCULA_REAJUSTE(P_SAL_ATUAL IN NUMBER) IS
        V_SAL_REAJ NUMBER(7,2);
    BEGIN
        V_SAL_REAJ := P_SAL_ATUAL * 1.25;
        DBMS_OUTPUT.PUT_LINE('SALÁRIO ATUAL - R$: ' ||P_SAL_ATUAL);
        DBMS_OUTPUT.PUT_LINE('SALÁRIO REAJUSTADO - R$: ' ||V_SAL_REAJ);
    END CALCULA_REAJUSTE;
    
    FUNCTION CONVERTE_DOLAR(V_DOLAR IN NUMBER) RETURN NUMBER IS
       v_cotacao NUMBER(10, 2) := 5.04;
       v_real    v_cotacao%type := v_cotacao * v_dolar;
    BEGIN
       RETURN 'Conversão US$ ' || v_dolar || ' em R$: ' || v_real;
    END CONVERTE_DOLAR;

END PKG_CALCULADORA;
/